"""add excluir_pedidos to ingredientes

Revision ID: 0ade3c6521f7
Revises: 23223cfeee9c
Create Date: 2026-07-13 19:00:11.265359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ade3c6521f7'
down_revision: Union[str, Sequence[str], None] = '23223cfeee9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredientes', sa.Column('excluir_pedidos', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredientes', 'excluir_pedidos')
    # ### end Alembic commands ###
