"""add precio_venta_bru2

Revision ID: 501dec99bdb0
Revises: 0ade3c6521f7
Create Date: 2026-07-24 12:24:44.815219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '501dec99bdb0'
down_revision: Union[str, Sequence[str], None] = '0ade3c6521f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recetas', sa.Column('precio_venta_bru2', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recetas', 'precio_venta_bru2')
    # ### end Alembic commands ###
