"""initial schema

Revision ID: 5b3701069a72
Revises: 
Create Date: 2026-07-11 20:48:52.377661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b3701069a72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('margen_objetivo', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('ingredientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('unidad_compra', sa.String(length=20), nullable=False),
    sa.Column('cantidad_compra', sa.Float(), nullable=False),
    sa.Column('precio_compra', sa.Float(), nullable=False),
    sa.Column('unidad_uso', sa.String(length=20), nullable=False),
    sa.Column('merma_porcentaje', sa.Float(), nullable=False),
    sa.Column('proveedor', sa.String(length=200), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_actualizacion', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recetas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('porciones_por_lote', sa.Integer(), nullable=False),
    sa.Column('precio_venta', sa.Float(), nullable=True),
    sa.Column('es_subreceta', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_modificacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_precios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.Column('precio_anterior', sa.Float(), nullable=False),
    sa.Column('precio_nuevo', sa.Float(), nullable=False),
    sa.Column('fecha_cambio', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lineas_receta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receta_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=True),
    sa.Column('subreceta_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ),
    sa.ForeignKeyConstraint(['subreceta_id'], ['recetas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lineas_receta')
    op.drop_table('historial_precios')
    op.drop_table('recetas')
    op.drop_table('ingredientes')
    op.drop_table('categorias')
    # ### end Alembic commands ###
