"""add orden and seccion to categorias

Revision ID: c55fba8b6f0b
Revises: 13321c0def7f
Create Date: 2026-07-26 00:00:07.924559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c55fba8b6f0b'
down_revision: Union[str, Sequence[str], None] = '13321c0def7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('orden', sa.Integer(), nullable=True))
    op.add_column('categorias', sa.Column('seccion', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categorias', 'seccion')
    op.drop_column('categorias', 'orden')
    # ### end Alembic commands ###
