"""Add grupo_ingrediente_id activo ubicacion for coffee tracking

Revision ID: d168f9d38ad7
Revises: ef9b6d1ac8ab
Create Date: 2026-07-30 00:53:08.441211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd168f9d38ad7'
down_revision: Union[str, Sequence[str], None] = 'ef9b6d1ac8ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredientes', sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('ingredientes', sa.Column('grupo_ingrediente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ingredientes', 'ingredientes', ['grupo_ingrediente_id'], ['id'])
    op.add_column('inventario_registros', sa.Column('ubicacion', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventario_registros', 'ubicacion')
    op.drop_constraint(None, 'ingredientes', type_='foreignkey')
    op.drop_column('ingredientes', 'grupo_ingrediente_id')
    op.drop_column('ingredientes', 'activo')
    # ### end Alembic commands ###
