"""Add lead_time_dias and ciclo_pedido_dias to proveedores

Revision ID: ef9b6d1ac8ab
Revises: c55fba8b6f0b
Create Date: 2026-07-29 20:08:35.433277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef9b6d1ac8ab'
down_revision: Union[str, Sequence[str], None] = 'c55fba8b6f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proveedores', sa.Column('lead_time_dias', sa.Integer(), server_default=sa.text('2'), nullable=False))
    op.add_column('proveedores', sa.Column('ciclo_pedido_dias', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proveedores', 'ciclo_pedido_dias')
    op.drop_column('proveedores', 'lead_time_dias')
    # ### end Alembic commands ###
